version: '2'

services:
  cloudera:
    image: cloudera/quickstart:latest
    command: bash -c "/root/startup.sh; sudo /home/cloudera/clouder-manager --pause --express"
    tty: true
    privileged: true
    hostname: quickstart.cloudera
    ports:
      - "8020:8020"
      - "2222:22"     # ssh
      - "7180:7180"   # Cloudera Manager
      - "8888:8888"   # HUE
      - "11000:11000" # Oozie
      - "50070:50070" # HDFS REST Namenode
      - "2181:2181"
      - "11443:11443"
      - "9090:9090"
      - "8088:8088"
      - "19888:19888"
      - "9092:9092"
      - "8983:8983"
      - "16000:16000"
      - "16001:16001"
      - "8042:8042"
      - "60010:60010"
      - "8080:8080"
      - "7077:7077"

    networks:
      - cloudera

networks:

  cloudera:
    driver: bridge
